name: Generate a report with gmuv

on:
  push
jobs:
  run-gmuv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate report for a test repository
        uses: groovy-sky/gmuv@v1.0.2
        with:
          account: 'groovy-sky'
          repository: 'aaa'