name: Generate reports with gmuv

on:
  push:
    paths:
    - '.github/workflows/*'
  schedule:
    - cron: '0 3 */7 * *'

jobs:
  run-gmuv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repos: ['benchpress','azure-cosmos-dotnet-v3','AgentBaker','bicep','azure-osconfig','azure-openapi-validator','azure-powershell','PSDocs.Azure']
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Generate report for Azure repos
        uses: groovy-sky/gmuv@v1.1.1
        with:
          account: 'Azure'
          repository: ${{ matrix.repos }}
          filename: REPORTS/Azure-${{ matrix.repos }}.md

      - name: Publishing the changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m $(date +%F)
          git push --force