name: Generate a report with gmuv

on:
  push
jobs:
  run-gmuv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repos: ['azure-quickstart-templates','Azure-DataFactory','autorest','AzOps']
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Generate report for Azure repo
        uses: groovy-sky/gmuv@v1.1.1
        with:
          account: 'Azure'
          repository: ${{ matrix.repos }}
          filename: REPORTS/Azure-${{ matrix.repos }}.md

      - name: Publishing the changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m $(date +%F)
          git push